### ISSUE TITLE
Notification is sent to windowed players when they take damage even if they are currently focused on the game window.

### ISSUE THREAD

**Issue by CalXee** [Dolphin2Point1/DamageNotifier#1]
Playing in windowed mode and take damage causes a notification to appear every time.

Ideally this only happens if someone is on another tab and isn't focused on the game window.

**Comment by Dolphin2Point1** [comment]
glfw bad so its no longer a single mixin and double accessor mod

**Comment by Dolphin2Point1** [comment]
wait i think i'm wrong

**Comment by Dolphin2Point1** [comment]
i was very wrong
